const i18Obj = {
    "en":{
        "contactsLink":"contacts",
        "aboutLink":"about me",
        "educationLink": "education",
        "skillsLink":"skills",
        "languagesLink":"languages",
        "projectsLink": "my projects",
        "hobbyLink":"hobby",
        "name":"Nikita",
        "surname": "Kakurin",
        "details":"Personal details:",
        "birthday":' Date of Birth: 08.09.1987;',
        "Marital":"Marital status: married;",
        "contactsTitle":"Contacts:",
        "address":"Voronezh, Russia;",
        "languagesTitle":"Languages:",
        "langEn":"English (level: pre-intermediate)",
        "langRu":"Russian",
        "CertificatesTitle":'Certificates:',
        "hobbiesTitle":"Hobbies:",
        "read":"read books",
        "play":"play chess",
        "aboutTitle":"About me:",
        "aboutText":`Hi, I am currently working as an electrical engineer. I have a higher education in the field of automation of production systems, but I really want to become a frontend developer. I started studying programming many times, but for a number of life reasons I temporarily stopped studying, but the desire to learn does not leave me. Now I am ready to work as frontend developer.`,
        "exampleTitle":"Example of my code:",
        "codewarsOld":"I have old profile of codewars which I used in 2016-2017 ",
        "codewarsNew": "started a new profile for rsschool course ",
        "shortExample":"short example of my code from ",
        "functionDescription": "function which returns square every digit:",
        "demoTitle": "Demo:",
        "please": "Please input value from 0 to 999",
        "projectsTitle": "My projects:",
        "portfolioName":'Site "Portfolio"',
        "virtualKeyboard": 'APP "Virtual-Keyboard"',
        "fileManager":"CLI file manager",
        "2048Name":'Game "2048"',
        "movieAppName":'Site "Movie-app"',
        "ecoName":'Site "Eco-sounds"',
        "drumName":'Music app "Drum-kit"',
        "experienceTitle":"Professional experience:",
        "experienceText":"I have some experience, I have made several games and several template-based websites using Webpack to build.",
        "educationTitle":"Education:",
        "educationUniversity":"2004-2009: Ukraine, Alchevsk, Donbass State Technical University - Electronic Engineering Engineer.",
        "skillsTitle":"skills:",
        "author":"Author: Kakurin Nikita",
    },
    "ru":{
        "contactsLink":"контакты",
        "aboutLink":"обо мне",
        "educationLink": "образование",
        "skillsLink":"навыки",
        "languagesLink":"языки",
        "projectsLink": "мои проекты",
        "hobbyLink":"хобби",
        "name":"Никита",
        "surname": "Какурин",
        "details":"Персональные данные:",
        "birthday":' Дата рождения: 08.09.1987;',
        "Marital":"Семейное положение: женат;",
        "contactsTitle":"Контакты:",
        "address":"Воронеж, Россия;",
        "languagesTitle":"Языки:",
        "langEn":"Английский (уровень: pre-intermediate)",
        "langRu":"Русский",
        "CertificatesTitle":'Сертификаты:',
        "hobbiesTitle":"Хобби:",
        "read":"читать книги",
        "play":"шахматы",
        "aboutTitle":"Обо мне:",
        "aboutText":`Привет, в настоящее время я работаю инженером-электриком. У меня высшее образование в области автоматизации производственных систем, но я действительно хочу стать фронтенд-разработчиком. Я много раз начинал изучать программирование, но по ряду жизненных причин временно прекращал учебу, но желание учиться меня не покидает. Теперь я готов работать фронтенд-разработчиком.`,
        "exampleTitle":"Примеры моего кода:",
        "codewarsOld":"У меня есть старый профиль codewars который я использовал в 2016-2017г. ",
        "codewarsNew": "я начал новый профиль для rsschool курсов ",
        "shortExample":"короткий пример моего кода ",
        "functionDescription": "функция которая фозвращает квадрат каждой цифры",
        "demoTitle": "Демо:",
        "please": "Пожалуйста введите число от 0 до 999",
        "projectsTitle": "Мои проекты:",
        "portfolioName":'Сайт "Portfolio"',
        "fileManager":"CLI файловый менеджер",
        "virtualKeyboard": 'APP "Виртуальная-клавиатура"',
        "2048Name":'Игра "2048"',
        "movieAppName":'Сайт "Movie-app"',
        "ecoName":'Сайт "Eco-sounds"',
        "drumName":'Music app "Drum-kit"',
        "experienceTitle":"Професиональный опыт:",
        "experienceText":"У меня есть некоторый опыт, я сделал несколько игр  и несколько  сайтов на основе шаблона используя  Webpack для сборки.",
        "educationTitle":"Образование:",
        "educationUniversity":"2004-2009: Украина, Алчевск, Доннбасский Государственный Технический Университет - Инженер электронной техники.",
        "skillsTitle":"Навыки:",
        "author":"Автор: Какурин Никита",
    }
}

export default i18Obj;